#!/usr/bin/env python3
"""This module takes a loaded language model
and a prompt to generate a response from the model.
"""


def get_response(llm, prompt):
    """
    Take a loaded language model and a prompt to generate
    a response from the model.

    Args:
        llm: An instance of a LangChain LLM.
        prompt: the question or instruction to pass to the model.

    Returns:
        AIMessage: The full response object generated by the LLM.
    """
    AIMessage = llm.invoke(prompt)

    return AIMessage
