#!/usr/bin/env python3
"""
This module generates a detailed classification report using Scikit-learn.
"""
from sklearn import metrics


def evaluate(true_labels, predicted_labels, class_names):
    """
    Generate a detailed classification report using Scikit-learn.
    This report should provide a comprehensive summary of the
    model’s performance for each class, including:
        - precision.
        - recall.
        - F1-score.

    Args:
        true_labels: Ground truth labels.
        predicted_labels: Predicted labels.
        class_names: List of class names corresponding to the label indices.

    Returns:
        A string containing the classification report
        generated by Scikit-learn.
    """
    detailed_report = metrics.classification_report(
        true_labels,
        predicted_labels,
        target_names=class_names
        )
    return detailed_report
